---
- name: Actualizar la cache de apt
  apt:
    update_cache: yes

- name: Instalar Podman
  apt:
    name: podman
    state: present

- name: Pull y desplegar contenedor del servidor web desde ACR
  containers.podman.podman_container:
    name: webserver
    image: "{{ acr_name }}.azurecr.io/app-vm:cp2"
    state: started
    restart_policy: always
    ports:
      - "80:80"