---
- name: Crear el namespace en AKS
  k8s:
    kubeconfig: "/home/martaavi/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: myappnamespace

- name: Desplegar la aplicación en AKS
  community.kubernetes.k8s:
    state: present
    kubeconfig: "/home/martaavi/.kube/config"
    context: "miAKS"
    definition: "{{ lookup('template', role_path + '/templates/app_deployment.yml.j2') }}"
    namespace: myappnamespace
